// This file is generated by Slice Machine. Update with care!

import SpaceTraveling from './SpaceTraveling';

export {
	SpaceTraveling,
};

export const components = {
	space_traveling: SpaceTraveling,
};
